name: Build Linux

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      name:
        description: 'Version name (default is ref name)'

env:
  VERSION: ${{ github.event.inputs.name || github.ref_name }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
    steps:
      - name: Process Version
        run: |
          TAG_VERSION=$(echo "${{ env.VERSION }}" | sed 's/^[vV]//')
          if ! [[ $TAG_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "version ${{ env.VERSION }} error."
            exit 1
          fi
          echo "GITHUB_VERSION=$TAG_VERSION" >>$GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v6

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y qt5-qmake qt5-qmake-bin qtbase5-dev qtbase5-dev-tools
          sudo apt-get install -y libqt5core5a libqt5gui5 libqt5widgets5 libqt5network5 libqt5x11extras5-dev
          sudo apt-get install -y build-essential libopencv-dev libxtst-dev libxrandr-dev libx11-dev
          sudo apt-get install -y cmake

      - name: Build and Package
        run: |
          cmake -Bbuild -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j$(nproc)
          cmake --build build --target package
          mv build/screenshot.deb screenshot-${{ matrix.os }}.deb
          mv build/screenshot.deb.sha256 screenshot-${{ matrix.os }}.deb.sha256
          ls


      - name: Upload deb
        uses: actions/upload-artifact@v6
        with:
          name: screenshot-${{ github.job }}-${{ matrix.os }}
          path: |
            screenshot-${{ matrix.os }}.deb
            screenshot-${{ matrix.os }}.deb.sha256

